<?php

include '../../includes/auth.php';
include '../../db.php';

if(!can('settings_view')){
    die("Access Denied");
}

$pageTitle="Data Export";

include '../../includes/header.php';
include '../../includes/sidebar.php';

?>

<link rel="stylesheet" href="../assets/style.css">


<div class="profile-page">

<div class="profile-header">

<div>

<h1>

<i class="fa-solid fa-file-export"></i>

Data Export

</h1>

<p>

Export application data in different formats.

</p>

</div>

<a
    href="../index.php"
    class="btn btn-dark"
>

<i class="fa-solid fa-arrow-left"></i>

Back

</a>

</div>

<div class="profile-grid">

<div class="profile-card">

<div class="profile-card-header">

<h3>

<i class="fa-solid fa-download"></i>

Export Modules

</h3>

</div>

<div class="profile-body">
    <div class="export-list">

    <a
        href="export.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-users"></i>

                Users

            </h4>

            <p>

                Export all user records.

            </p>

        </div>

        <span class="badge bg-primary">

            CSV

        </span>

    </a>

    <a
        href="export-clients.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-address-book"></i>

                Clients

            </h4>

            <p>

                Export all client information.

            </p>

        </div>

        <span class="badge bg-success">

            CSV

        </span>

    </a>

    <a
        href="export-quotations.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-file-invoice"></i>

                Quotations

            </h4>

            <p>

                Export quotations with pricing.

            </p>

        </div>

        <span class="badge bg-warning text-dark">

            Excel

        </span>

    </a>

    <a
        href="export-materials.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-layer-group"></i>

                Materials

            </h4>

            <p>

                Export carcass and shutter materials.

            </p>

        </div>

        <span class="badge bg-info text-dark">

            Excel

        </span>

    </a>

    <a
        href="export-accessories.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-screwdriver-wrench"></i>

                Accessories

            </h4>

            <p>

                Export accessories and pricing.

            </p>

        </div>

        <span class="badge bg-secondary">

            Excel

        </span>

    </a>

    <a
        href="export-complete-backup.php"
        class="export-item"
    >

        <div>

            <h4>

                <i class="fa-solid fa-box-archive"></i>

                Complete Database

            </h4>

            <p>

                Export complete application data.

            </p>

        </div>

        <span class="badge bg-danger">

            SQL

        </span>

    </a>

</div>

</div>

</div>

<div class="profile-card">

<div class="profile-card-header">

<h3>

<i class="fa-solid fa-circle-info"></i>

Export Information

</h3>

</div>

<div class="profile-body">
    <div class="profile-item">

    <div class="profile-label">

        <i class="fa-solid fa-file-csv"></i>

        CSV Export

    </div>

    <div class="profile-value">

        Compatible with Microsoft Excel, Google Sheets and LibreOffice.

    </div>

</div>

<div class="profile-item">

    <div class="profile-label">

        <i class="fa-solid fa-file-excel"></i>

        Excel Export

    </div>

    <div class="profile-value">

        Includes formatted worksheets and structured data.

    </div>

</div>

<div class="profile-item">

    <div class="profile-label">

        <i class="fa-solid fa-database"></i>

        SQL Backup

    </div>

    <div class="profile-value">

        Complete database dump for backup and migration.

    </div>

</div>

<div class="profile-item">

    <div class="profile-label">

        <i class="fa-solid fa-clock"></i>

        Generated On

    </div>

    <div class="profile-value">

        <?= date('d M Y h:i A'); ?>

    </div>

</div>

<div class="profile-item">

    <div class="profile-label">

        <i class="fa-solid fa-user"></i>

        Generated By

    </div>

    <div class="profile-value">

        <?= htmlspecialchars($_SESSION['name']); ?>

    </div>

</div>

</div>

</div>

</div>


<?php include '../../includes/footer.php'; ?>